module.exports = {
    eng: {
        login: {
            title: 'ABSENCES MANAGERMENT',
            description: 'Sign in with your email and password:',
            email: 'Email',
            password: 'password',
            login: 'login',
            forgotPass: 'Forgot Password?',
            langKhmer: 'Khmer',
            langEnglish: 'English',
            credentials: 'Credentials not match.',
            userId: 'User ID',
        },
        forgotPass: {
            title: "Forgot your password?",
            description1: "Enter your email address that you used to login.",
            description2: "we'll send you a link to reset your password.",
            email: 'Email',
            backToLogin: 'Back to Login',
            btnResetPass: 'reset password'
        },
        app: {
            title: 'Khawin Management System',
            monday: 'Monday',
            tuesday: 'Tuesday',
            wednesday: 'Wednesday',
            thursday: 'Thursday',
            friday: 'Friday',
            saturday: 'Saturday',
            sunday: 'Sunday',
            january: 'January',
            february: 'February',
            march: 'March',
            april: 'April',
            may: 'May',
            june: '/06',
            july: 'July',
            august: 'August',
            september: 'September',
            october: 'October',
            november: 'November',
            december: 'December',
        },
        holiday: {
            title: 'Cambodia Public holiday for',
            addHoliday: 'add holiday',
            tbDay: 'Day',
            tbDate: 'Date',
            tbHoliday: 'Holiday',
            tbAction: 'Edit | Delete',
            frmtitleAdd: 'Add Holiday',
            frmtitleEdit: 'Edit Holiday',
            txtHolidayDate: 'Holiday Date',
            txtHolidayDetail: 'Holiday Detail',
            btnCancel: 'cancel',
            btnSave: 'save',
            monday: 'Monday',
            tuesday: 'Tuesday',
            wednesday: 'Wednesday',
            thursday: 'Thursday',
            friday: 'Friday',
            saturday: 'Saturday',
            sunday: 'Sunday',
            january: 'January',
            february: 'February',
            march: 'March',
            april: 'April',
            may: 'May',
            june: 'June',
            july: 'July',
            august: 'August',
            september: 'September',
            october: 'October',
            november: 'November',
            december: 'December',
        },
        Holiday: {
            holiday: 'Holiday',
            btnAddHoliday: 'Add',
            Description: 'Description',
            HolidayDate: 'Holiday Date',
            Allowed: 'Allowed',
            NotAllowed: 'Not Allowed',
            HolidayType: 'Holiday Type',
        },
        staffPosition: {
            StaffPosition: 'Staff Position',
            btnAdd: 'Add',
            employee: 'Employee',
            position: 'Position',
            startDate: 'Start Date',
            endDate: 'End Date',    
        },
        menu: {
            dashboard: 'Dashboard',
            position: 'Position',
            employee: 'employee',
            employeeList: 'List',
            absent: 'Absent',
            absentList: 'List',
            report: 'Report',
            user: 'User',
            setting: 'Setting',
            account: 'Account',
            signout: 'sign out',
            role: 'role',
            validation: 'Validation',
            leaveRequest: 'Leave Request',
            Inventory: 'Asset',
            AddStock: 'AddStock',
            issueItem: 'IssueItem',
            ReturnItem: 'ReturnItem',
            humanResourceSetting: 'Human Resource',
            branchSetting: 'Branch',
            departmentSetting: 'Department',
            resignationSetting: 'Resignation Reason',
            leaveTypeSetting: 'Leave Type',
            leaveReason:'Leave Reason',
            inventorySetting: 'asset',
            addItem: 'addItem',
            AssetCategory: 'Asset Category',
            itemSupplier: 'itemSupplier',
            itemStore: 'itemStore',
            HumanResource:'Human Resource',
            StaffAttendance:'StaffAttendance',
            PayRoll:'PayRoll',
            ApplyLeave:'Apply Leave',
            ApproveStaffLeave:'Approve StaffLeave',
            StaffRating:'Staff Rating',
            StaffResignation:'Staff Resignation',
            StaffInformation: 'Staff  Information',
            systemSetting:'System Setting',
            accountSystemSetting:'Account',
            userSystemSetting:'User',
            roleSystemSetting:'Role',
            parameter:'Parameter',
            WorkFlow:'WorkFlow',
            menuSystemSetting: 'Menu',
            shift: 'Shift',
            Staff: 'Staff',
            Attendance: 'Attendance',
            LeaveEntry: 'Attendance List',
            CalculatePayroll: 'Calculate Payroll',
            BasicSalary: 'Basic Salary',
            Holiday: 'Holiday',
            StaffPosition: 'Staff Position',
            DocumentForm: 'Document Form',
            Document: 'Document',
            SystemLog: 'System Log',
            StaffShift: 'Staff Shift',
        },
        languages: {
            language: 'Language',
            'english': 'English',
            'khmer': 'Khmer',
        },
        dashboard: {
            title: 'Dashboard',
            users: 'Users',
            employee: 'Employees',
            absent: 'Absent',
            weekly: 'This Week',
            monthly: 'This Month',
            yearly: 'This Year',
            absenceSummary: 'Absence Summary',
            day: 'day',
            fullDay: 'full day',
            halfDay: 'half day',
            monday: 'Monday',
            tuesday: 'Tuesday',
            wednesday: 'Wednesday',
            thursday: 'Thursday',
            friday: 'Friday',
            saturday: 'Saturday',
            sunday: 'Sunday',
            january: 'January',
            february: 'February',
            march: 'March',
            april: 'April',
            may: 'May',
            june: 'June',
            july: 'July',
            august: 'August',
            september: 'September',
            october: 'October',
            november: 'November',
            december: 'December',
            todayAbsent:'Today Absent',
            validation:'Validation',
            total: 'Total',
            No: "No",
        },
        position: {
            titleList: 'Position List',
            search: 'Search',
            addPosition: 'add position',
            positionTable: 'Position',
            tabelNotFound: 'Not Found Data',
            employeeCountTable: 'Employee',
            edit_delete: 'Edit | Delete',
            tablePagination: 'Rows per page',
            positionEmpProfile: 'Profile',
            positionEmpName: 'Name',
            formTitleAdd: 'Add Position',
            formTitleEdit: 'Edit Position',
            txtPosition: 'Position Name',
            btnCancel: 'cancel',
            btnSave: 'save',
            btnDelete: 'delete',
            deleteMessage: 'Are you sure delete position',
            deleteMessageWarning: 'All employee in this positon will be delete too',
            msgClose:'close',
            savedMsg: 'Position has been saved.',
            updateMsg: 'Position has been updated.',
            deleteMsg: 'Position has been deleted.',
            // Modify by Huychoung 02/08/2023 #82
            notAllowedWarningMessage: 'Cannot delete position',
            warningMessage: 'Because it is being used.',
            parentPosition: 'Parent Position',
            Department: 'Department',
            
        },

        employee: {
            employeeName: 'Employee',
            list: 'Employees List',
            search: 'Search',
            btnAddEmp: 'add employee',
            activeEmp: 'Active Employee',
            tabAddEmp: 'Add Employee',
            inctiveEmp: 'Inactive Employee',
            tbStaffCode: 'Staff Code',
            tbName: 'Name',
            tbGender: 'Gender',
            tbGenderM: 'male',
            tbGenderF: 'female',
            tbOtherName: 'Other Name',
            tbEmail: 'Email',
            tbPosition: 'Position',
            tbStartDate: 'Start Date',
            tbStartStopDate: 'Date Sarted | Stopped',
            tbPhoneNum: 'Phone Number',
            tbShift: 'Shift',
            tbEditDelete: 'edit | delete',
            tabelNotFound: 'Not Found Data',
            tablePagination: 'Rows per page',
            frmAddEmp: 'Add Employee',
            frmEditEmp: 'Edit Employee',
            staffCode: 'Staff Code',
            txtFirstName: 'First Name*',
            txtLastName: 'Last Name*',
            genderF: 'Female',
            genderM: 'Male',
            txtOtherName: 'Other Name',
            txtEmail: 'Email*',
            role:'Role*',
            selectPosition: 'Select Position*',
            selectShift: 'Select Shift*',
            txtUserID: 'User ID or Phone Number*',
            txtStartDate: 'Start Date*',
            txtPhoneNum: 'Phone Number*',
            txtNationalID: 'National ID',
            txtBirthDate: 'Birth Date',
            txtBirthPlace: "Birth Place",
            txtHouseNo: "House No",
            txtStreetNo: "Street No",
            txtProvince: "Province",
            txtDistrict: "District",
            txtCommune: "Commune",
            txtVillage: "Village",
            txtFacebook: "Facebook",
            txtTelegram: "Telegram",
            txtOtherContact: "Otherr Contact",
            btnCancel: 'cancel',
            btnSave: 'save',
            empImage: 'Employee Image',
            isInactive: 'Is Inactive',
            leavedDate: 'Leave Date',
            january: '01',
            february: '02',
            march: '03',
            april: '04',
            may: '05',
            june: '06',
            july: '07',
            august: '08',
            september: '09',
            october: '10',
            november: '11',
            december: '12',
            btnDelete: 'delete',
            deleteMessage: 'Are you sure delete employee',
            msgClose:'close',
            savedMsg: 'Employee data save successfully.',
            updateMsg: 'Employee has been updated.',
            deleteMsg: 'Employee has been deleted.',
            labelChildren: "Children List.",
            AddEmp:'Add Employee',
            tbChildName: 'Children Name',
            ChildList: 'Children',
            OtherSkillList: 'OtherSkill',
            ExperienceList: 'Experience',
            LanguageList: 'Language',
            ReferenceList: 'Reference',
            Remark: 'Remark',
            EducationList: 'Education',
            tbSchoolName: 'SchoolName' ,
            tbAddress: 'Address',
            tbStartDate: 'StartDate',
            tbEndDate: 'EndDate',
            tbSkill: 'Skill',
            tbDetail: 'Detail',
            tbTrainingPlace: 'Traning Place',
            txtPosition: 'Position',
            tbLanguage: 'Language',
            tbLevel: 'Level',
            tbCompany: 'Company',
            tbFullName: 'Reference Name',
            warningSaveMessage: 'Please save staff information first!',
            saveChildren: 'Children data save successfully',
            updateChildren: 'Children list has been update',
            saveEducation: 'Education data save successfully',
            updateEducation: 'Education list has been update',
            saveOtherSkill: 'OtherSkill data save successfully',
            updateOtherSkill: 'OtherSkill list has been update',
            saveExperience: 'Experience data save successfully',
            updateExperience: 'Experience list has been update',
            saveLanguage: 'Language data save successfully',
            updateLanguage: 'Language list has been update',
            saveReference: 'Reference data save successfully',
            updateReference: 'Reference list has been update',
        },
        absent: {
            listTitle: 'ApplyLeave',
            search: 'Search',
            btnAdd: 'add absent',
            tbEmp: 'Employee',
            tbAbsent: 'Absent',
            tbDay: 'Day',
            tbDate: 'Date',
            tbDescription: 'Description',
            tbEdit_Delete: 'Edit | Delete',
            tbPagination: 'Rows per page',
            tabelNotFound: 'Not Found Data',
            fullDay: 'full day',
            halfDay: 'half day',
            morning: 'morning',
            afternoon: 'afternoon',
            monday: 'Monday',
            tuesday: 'Tuesday',
            wednesday: 'Wednesday',
            thursday: 'Thursday',
            friday: 'Friday',
            saturday: 'Saturday',
            sunday: 'Sunday',
            frmTitleAdd: 'Add Absent',
            frmTitleEdit: 'Edit Absent',
            frmSelect: 'Select Employee',
            frmFullDay: 'Full Day',
            frmHalfDay: 'Half Day',
            frmAbsentDate: 'Absent Date',
            frmMorning: 'Morning',
            frmAfternoon: 'Afternoon',
            frmDescription: 'Description',
            frmCancel: 'cancel',
            frmSave: 'save',
            january: 'January',
            february: 'February',
            march: 'March',
            april: 'April',
            may: 'May',
            june: 'June',
            july: 'July',
            august: 'August',
            september: 'September',
            october: 'October',
            november: 'November',
            december: 'December',
            deleteMsg: 'Are you sure?',
            deleteMsgAlert: 'Delete',
            deleteMsgAlertAbsen: "absent",
            btnCancel: 'cancel',
            btnDelete: 'Delete',
            deleteMessage: 'Are you sure delete',
            msgClose:'close',
            savedMsg: 'Absent has been saved.',
            updateMsg: 'Absent has been updated.',
            deleteMsg: 'Absent has been deleted.',
            today:'Absent',
            reason:'Leave Reason',
            type:'Leave Type',
            remark:'Remark',
            btnApplyLeave:'Apply',
            btnSave:'Save',
            btnSubmit:'Submit',
            attendance:'Attendance',
            absentTime:'Absent Time',
            LeaveDetail:'Detail',
        },
        report: {
            title:  'Report',
            tbEmployee: 'Employee',
            tbAbsentCount: 'Absent Count',
            tbTotalAbsent: 'Total Absent',
            tbPosition: 'Position',
            tbAbsent: 'Absent',
            tbDay: 'Day',
            tbDate: 'Date',
            tbDescription: 'Description',
            notReport: 'please select date or employee',
            txtDate: 'Choose Date',
            txtSelectEmp: 'Select Employee',
            smgAlert: 'Please choose any Date or Employee.',
            btnReport: 'Report',
            tbPagination: 'Rows per page',
            fullDay: 'full day',
            halfDay: 'half day',
            morning: 'morning',
            afternoon: 'afternoon',
            day: 'day',
            monday: 'Monday',
            tuesday: 'Tuesday',
            wednesday: 'Wednesday',
            thursday: 'Thursday',
            friday: 'Friday',
            saturday: 'Saturday',
            sunday: 'Sunday',
            january: '01',
            february: '02',
            march: '03',
            april: '04',
            may: '05',
            june: '06',
            july: '07',
            august: '08',
            september: '09',
            october: '10',
            november: '11',
            december: '12',
            pdfHeaderTb: 'Absent List',
            pdfTitle: 'Absent Report',
            pdfReportBy: 'Report By',
            pdfDateReport:'Report Date'
        },
        user: {
            listTitle: 'User List',
            btnAdd: 'add user',
            tbName: 'User ID',
            tbEmail: 'Email',
            tbRole: 'Role',
            tbPhoneNum: 'Phone Number',
            tbUpdate_Delete: 'Edit | Delete',
            tbPagination: 'Rows per page',
            frmTitleAdd: 'Add User',
            txtRole: 'Role',
            txtName: 'Name',
            txtEmail: 'Email',
            txtPhone: 'Phone Number',
            txtPassword: 'Password',
            txtPasswordConfir: 'Password Confirmation',
            txtImage: 'select image',
            btnCancel: 'cancel',
            btnSave: 'save',
            btnDelete: 'Delete',
            deleteMessage: 'Are you sure delete user',
            msgClose:'close',
            savedMsg: 'User has been saved.',
            updateMsg: 'User has been updated.',
            deleteMsg: 'User has been deleted.',
            txtUserID: 'UserID',
            txtUserName: 'User Name',
        },
        account: {
            tabAccount: 'Account',
            tabPassword: 'Password',
            txtName: 'Name',
            txtEmail: 'Email',
            Password: 'Password',
            txtPassword: 'Password',
            txtNewPassword: 'New Password',
            txtConfirPassword: 'Confirm Password',
            btnSave: 'save',
            msgClose:'close',
            updateMsg: 'Profile has been updated.',
            passUpdateMsg: 'Password updated please login again.'
        },
        role: {
            role: 'Role',
            tbRole: 'Role',
            tbMenu: 'Menu',
            tbDescription: 'description',
            tbUser: 'User',
            frmNameAdd: 'Add Role',
            frmNameEdit: 'Update Role',
            txtRole: 'Role Name',
            txtDescrition: 'Description',
            lblSelectMenu: 'Select Menu',
            btnAddRole: 'Add Role',
            btnCancel: 'cancel',
            btnSave: 'save',
        },
        workflow:{
            listWorkflow:'Workflow',
            btnAdd:'Add',
            group:'Group',
            frmTitle:'Add Workflow',
            frmEditTitle:'Edit Workflow',
            workflowCode:'Workflow Code',
            workflowName:'Workflow Name',
            groupCode:'Group Code',
            groupName:'Group Name',
            user:'User',
            deleteMessage:'Are you sure to delete',
            createDate:'Create Date',
            order:'Order',
            addTable:'Please input a date and time.',
            groupTable: 'Please select a group.',
            userGroup:'Please select a user.',
            position:'Please select a position',
            empity:'Group must be unique.',
            btnClick: 'Please insert workflow group ==>',
            labelPosition:'Position',
            NoPosition:'This type is no position to select.',
            labelWorkflowGroup:'Workflow Group',
        },
        parameters: {
            listParameter:'List Parameter',
            frmTitle:'Add Parameter',
            parameter:'Parameter',
            value1:'Value 1',
            value2:'Value 2',
            frmEditTitle:'Edit Parameter',
            txtValidation:'Validation Type',
            txtkh:'Khmer',
            txten:'English',
            txtth:'ThaiLand',
            txtch:'China',
            txtfr:'France',
            txtvn:'Vietnam',
        },
        leaveRequest:{
            list:'Leave Request',
            applied:'Applied Leave',
            history:'History',
            btnApprove:'Approve',
            btnReject:'Reject',
            detail:'Detail',
            comment:'Comment',
            shiftList:'Shift',
            code:'Code',
            name:'Name',
            section:'Section',
            timeIn:'Time In',
            timeOut:'Time Out',
            frmAddtime:'Add Time Work',
            frmEditTime:'Edit Time Work',
            msgClose:'Close',
            msgApprove:'Your data has been updated.',
            msgReject:'Your data has been rejected.',
        },
        leaveEntry:{
            btnExport: 'Export Excel',
            listLeaveEntry:'Attendance List',
            frmTitle:'Add Absent',
            frmEditTitle:'Edit Absent',
            frmAdd: 'Add Attendance list by department',
            frmEdit: 'Edit Attendance list by department',
            department: 'Department',
            tbAbsent:'Absent',
            tbTime:'Time',
            tbEmpName:'Employee',
            tbReason:'Reason',
            tbStatus:'Status',
            tbType:'LeaveType',
            tbRemark:'Remark',
            tbAttendanceDate:'Attendance Date',
            tbAction:'Edit|Delete',
            leaveReason:'Leave Reason',
            btnAdd:'Add by Department',
            frmAddReason:'Add Reason',
            frmEditReason:'Edit Reason',
            frmLeaveType:'Add Leave Type',
            frmEditLeaveType:'Edit Leave Type',
            btnAddLeaveType:'Add',
            txtAllowance:'Allowance',
            txtDeduction:'Deduction',
            submiteDate:"Submite Date",
            detail:'Detail',
            msgSaved:'Your data has been saved.',
            msgDelete:'Your data has been deleted.',
            msgUpdate:'Your data has been updated.',
            filterByDate: "Filter by date",
            startDate: "Start Date",
            endDate: "End Date",
            filterByType: "Filter by type",
            quickFilter: "Quick filter",
            today: "Today",
            weekly: "Weekly",
            monthly: "Monthly",
            yearly: "Yearly",
            search: "Search",
            msgEmpity: 'Data can not be empity.',
            labelDateTime: "Absent Attendance date and time.",
            msgExist: "Data is already existed.",
            msgDuplicate: "Data is duplicated.",
            validationDate: 'Attendance can not be empty.',
            validationTime: 'Time can not be empty.',
            tbPermission: 'Permission',
        },
        branch:{
            branchList:'Branch',
            frmAddBranch:'Add Branch',
            frmEditBranch:'Edit Branch',
            txtCode:'Code',
            txtBranch:'Branch',
            txtLocation:'Location',
            txtStartDate:'Start Date',
            txtEndDate:'End Date',
        },
        menuSetting:{
            menuList:'Menu',
            frmAddMenu:'Add Menu',
            frmEditMenu:'Edit Menu',
            txtMenuCode:'Code',
            menuName:'Menu Name',
            connection:'Connection',
            MainCode:'Main Code',
            Sign:'Sign',
            Type:'Type',
            Order:'Order',
            Closed:'Closed',
        },
        department:{
            //Modify by Huychoung 04/08/2023 #84
            listDepartment:'Department',
            frmAddDepartment:'Add Department',
            frmEditDepartment:'Edit Department',
            department:'Department',
            parentDepartment: 'Parent Department',
            Remark: 'Remark',
            warningMessage: 'is being used in :',
        },
        document:{
            documentList: 'Document',
            btnAdd: 'Add',
            btnDelete: 'Delete',
            btnExport: 'Export',
            frmAddDocument: 'Add Document',
            frmDocumentCode: 'Document Code',
            frmTitle: 'Title',
            frmType: 'Type',
            frmContentKH: 'Content KH',
            frmContentEN: 'Content EN',
            frmDescriptionKH: 'Description KH',
            frmDescriptionEN: 'Description EN',
            tbCheckbox: '',
            tbDocumentCode: 'Document Code',
            tbTitle: 'Title',
            tbType: 'Type',
            tbContentKH: 'Content KH',
            tbContentEN: 'Content EN',
            tbDescriptionKH: 'Description KH',
            tbDescriptionEN: 'Description EN',
            tbAction: 'Action',
            DialogWarning: 'Please select an item',
            tbFileName: 'File Name',
        },
        applyLeave:{
            msgSubmit: 'Your data has been submited.',
            msgEmpity: 'Date and time can not be empty.',
            msgDuplicate: 'Date and time can not duplicate.',
            msgExist: 'Date and time is already exist.',
            msgDateTime: 'Please select a date and time.',
            msgAttendance: 'Please select attendance.',
            msgTime:'Please select time.',
            labelDateTime: 'Absent Attendance date and time'
        },
        systemLog:{
            tbActions: 'Edit | Delete',
            listSystemLog: 'System Log',
            btnAddSystemLog: 'Add System Log',
            tbMenuName: 'Menu Name',
            tbUser: 'User',
            tbAction: 'Action',
            tbOldData: 'Old Data',
            tbNewData: 'New Data',
            tbLogType: 'Log Type',
            tbMessage: 'Message',
            tbHostName: 'Host Name',
            tbDateTime: 'Time & Date',
        },
        shift: {
            labelDateTime: 'Section Time In and Time Out',
            msgEmpity: 'Please select time',
            msgDuplicate: 'TimeIn and TimeOut can not duplicate.',
            msgExist: 'TimeIn and TimeOut is already exist.',
        },
        staffShift: {
            addShift: 'Add Shift',
            editShift: 'Edit Shift',
            deleteShift: 'Delete',
            tbEmployeeName: 'Employee Name',
            tbShiftName: 'Shift Name',
            tbStartDate: 'Start Date',
            tbEndDate: 'End Date',
            tbRemark: 'Remark',
            savedMsg: 'Staff Shift data save successfully.',
            updateMsg: 'Staff Shift has been updated.',
            deleteMsg: 'Staff Shift has been deleted.',
        },
        staffResignation: {
            staffResign: 'Staff Resignation',
            addFrm: 'Add Staff Resignation',
            editFrm: 'Edit Staff Resignation',
            employeePKID: 'Employee',
            resignationReasonPKID: 'Resignation Reason',
            description: 'Description',
            resignedDate: 'Resigned Date',
        },
        resignationReason: {
            resignReason: 'Resignation Reason',
            addFrm: 'Add Resignation Reason',
            editFrm: 'Edit Resignation Reason',
            reasonCode: 'Reason Code',
            description: 'Description', 
            exportExcel: 'Export Excel',
            exportPDF: 'Export PDF',
        },
    }
};
