module.exports = {
    kh: {
        login: {
            title: 'ប្រព័ន្ធគ្រប់គ្រង អវត្តន៏មាន',
            description: 'បំពេញអ៊ីម៉ែល និងពាក្យសំមង្ងាត់របស់អ្នក',
            email: 'អ៊ីម៉ែល',
            password: 'ពាក្យសម្ងាត់',
            login: 'ចូល',
            forgotPass: 'ភ្លេចពាក្យសម្ងាត់?',
            langKhmer: 'ខ្មែរ',
            langEnglish: 'អងគ្លេស',
            credentials: 'មិនត្រឹមត្រូវ',
            userId: 'លេខសម្គាល់អ្នកប្រើ',
        },
        forgotPass: {
            title: "ភ្លេចពាក្យសម្ងាត់របស់អ្នក?",
            description1: "បញ្ចូលអ៊ីម៉ែលរបស់អ្នក ដែរអ្នកធ្លាប់ប្រើដើម្បីចូលប្រព័ន្ធ",
            description2: "យើងនិងផ្ញើរដំណភ្ជាប់ទៅអ្នក ដើម្បីផ្លាស់ប្តូរពា្យសម្ងាត់របស់អ្នក",
            email: 'អ៊ីម៉ែល',
            backToLogin: 'ត្រឡប់ទៅទំព័រមុន',
            btnResetPass: 'ផ្លាស់ប្តូរពាក្យសម្ងាត់'
        },
        app: {
            title: 'ប្រព័ន្ធគ្រប់គ្រងទិន្នន័យរបស់ខាវីន',
            monday: 'ថ្ងៃចន្ទ',
            tuesday: 'អង្គារ',
            wednesday: 'ពុធ',
            thursday: 'ព្រហស្បតិ៍',
            friday: 'សុក្រ',
            saturday: 'សៅរ៍',
            sunday: 'អាទិត្យ',
            january: 'ខែមករា',
            february: 'ខែកុម្ភះ',
            march: 'ខែមិនា',
            april: 'ខែមេសា',
            may: 'ខែឧសភា',
            june: 'ខែមិថុនា',
            july: 'ខែកក្កដា',
            august: 'ខែសីហា',
            september: 'ខែកញ្ញា',
            october: 'ខែតុលា',
            november: 'ខែវិច្ឆកា',
            december: 'ខែធ្នូ',
        },
        holiday: {
            title: 'ថ្ងៃបុណ្យជាតិឈប់សំរាកសំរាប់ឆ្នាំ',
            addHoliday: 'បន្ថែមថ្ងៃឈប់សំរាក',
            tbDay: 'ថ្ងៃ',
            tbDate: 'ថ្ងៃខែឆ្នាំ',
            tbHoliday: 'ឈប់សំរាក',
            tbAction: 'កែប្រែ | លុប',
            frmtitleAdd: 'បន្ថែមថ្ងៃឈប់សំរាក',
            frmtitleEdit: 'កែប្រែថ្ងៃឈប់សំរាក',
            txtHolidayDate: 'កាលបរិច្ឆេទ ថ្ងៃឈប់សំរាក',
            txtHolidayDetail: 'ព័ត៌មានលម្អិតនៃថ្ងៃឈប់សម្រាក',
            btnCancel: 'បោះបង់',
            btnSave: 'រក្សាទុក',
            monday: 'ថ្ងៃចន្ទ',
            tuesday: 'អង្គារ',
            wednesday: 'ពុធ',
            thursday: 'ព្រហស្បតិ៍',
            friday: 'សុក្រ',
            saturday: 'សៅរ៍',
            sunday: 'អាទិត្យ',
            january: 'ខែមករា',
            february: 'ខែកុម្ភះ',
            march: 'ខែមិនា',
            april: 'ខែមេសា',
            may: 'ខែឧសភា',
            june: 'ខែមិថុនា',
            july: 'ខែកក្កដា',
            august: 'ខែសីហា',
            september: 'ខែកញ្ញា',
            october: 'ខែតុលា',
            november: 'ខែវិច្ឆកា',
            december: 'ខែធ្នូ',
        },
        Holiday: {
            holiday: 'ថ្ងៃឈប់សម្រាក',
            btnAddHoliday: 'បន្ថែម',
            Description: 'បរិយាយ',
            HolidayDate: 'ថ្ងៃសម្រាក',
            Allowed: 'អនុញ្ញាត',
            NotAllowed: 'មិនអនុញ្ញាត',
            HolidayType: 'ប្រភេទ',
        },
        staffPosition: {
            StaffPosition: 'តួនាទីបុគ្គលិក',
            btnAdd: 'បន្ថែម',
            employee: 'ឈ្មោះបុគ្គលិក',
            position: 'មុខតំណែង',
            startDate: 'ថ្ងៃចាប់ផ្ដើម',
            endDate: 'ថ្ងៃបញ្ចប់',    
        },
        menu: {
            dashboard: 'ផ្ទាំងទិន្នន័យ',
            position: 'មុខដំណែង',
            employee: 'បុគ្គលិក',
            employeeList: 'តារាងបុគ្គលិក',
            absent: 'អវត្តន៏មាន',
            absentList: 'តារាងអវត្តន៏មាន',
            report: 'របាយការណ៍',
            user: 'អ្នកប្រើប្រាស់',
            setting: 'ការកំណត់',
            signout: 'ចាកចេញ',
            account: 'គណនី',
            role: 'កំណត់សិទ្ធ',
            validation: 'ការកំណត់',
            leaveRequest: 'ច្បាប់ដែលបានស្នើសុំ',
            Inventory: 'ទ្រព្យសម្បត្តិក្រុមហ៊ុន',
            AddStock: 'បន្ថែមសម្ភារះ',
            issueItem: 'បញ្ចេញសម្ភារះ',
            ReturnItem: 'បញ្ចូលសម្ភារះវិញ',
            humanResourceSetting: 'ការិយាល័យធនធានមនុស្ស',
            branchSetting: 'សាខា',
            departmentSetting: 'ការិយាល័យ',
            resignationSetting: 'មូលហេតុលាឈប់',
            leaveTypeSetting: 'ប្រភេទច្បាប់',
            leaveReason :'មូលហេតុសុំច្បាប់',
            inventorySetting: 'ទ្រព្យសម្បត្តិក្រុមហ៊ុន',
            addItem: 'បន្ថែមឈ្មោះសម្ភារៈ',
            AssetCategory: 'ប្រភេទទ្រព្យ',
            itemSupplier: 'អ្នកផ្គត់ផ្គង់',
            itemStore: 'ឃ្លាំង',
            HumanResource:'ការរិយាល័យធនធានមនុស្ស',
            StaffAttendance:'វត្តមានបុគ្គលិក',
            designationSetting: 'តួនាទី',
            PayRoll:'ប្រាក់ខែ',
            ApplyLeave:'ស្នើច្បាប់',
            ApproveStaffLeave:'អនុញ្ញាតច្បាប់',
            StaffRating:'វាយតម្លៃបុគ្គលិក',
            StaffResignation:'បុគ្គលិកលាឈប់',
            StaffInformation: 'តារាងបុគ្គលិក',
            systemSetting:'គ្រប់គ្រងប្រព័ន្ធ',
            accountSystemSetting:'គណនី',
            userSystemSetting:'អ្នកប្រើប្រាស់',
            roleSystemSetting:'កំណត់សិទ្ធ',
            parameter:'កំណត់អញ្ញត្តិ',
            WorkFlow:'លំហូរការងារ',
            menuSystemSetting: 'មុខងារ',
            shift: 'ម៉ោងការងារ',
            Staff: 'បុគ្កលិក',
            Attendance: 'អវត្តមាន',
            LeaveEntry: 'បញ្ជីអវត្តមាន',
            CalculatePayroll: 'គណនាប្រាក់ខែ',
            BasicSalary: 'ប្រាក់ខែគោល',
            Holiday: 'ថ្ងៃឈប់សម្រាក',
            StaffPosition: 'តួនាទីបុគ្គលិក',
            DocumentForm: 'ឯកសារ និងទម្រង់លិខិត',
            Document: 'ឯកសារ',
            SystemLog: 'ប្រវត្តិ និងសារបញ្ហា',
        },
        languages: {
            language: 'ភាសា',
            'english': 'អង់គ្លេស',
            'khmer': 'ខ្មែរ',
        },
        dashboard: {
            title: 'ផ្ទាំងទិន្នន័យ',
            users: 'អ្នកប្រើប្រាស់',
            employee: 'បុគ្គលិក',
            absent: 'អវត្តមាន',
            weekly: 'សប្តាហ៍នេះ',
            monthly: 'ខែនេះ',
            yearly: 'ឆ្នាំនេះ',
            absenceSummary: 'សង្ខេបអវត្តមាន',
            day: 'ថ្ងៃ',
            fullDay: 'មួយថ្ងៃ',
            halfDay: 'កន្លះថ្ងៃ',
            morning: 'ពេលព្រឹក',
            afternoon: 'ពេលរសៀល',
            monday: 'ចន្ទ',
            tuesday: 'អង្គារ',
            wednesday: 'ពុធ',
            thursday: 'ព្រហស្បតិ៍',
            friday: 'សុក្រ',
            saturday: 'សៅរ៍',
            sunday: 'អាទិត្យ',
            january: 'មករា',
            february: 'កុម្ភះ',
            march: 'មិនា',
            april: 'មេសា',
            may: 'ឧសភា',
            june: 'មិថុនា',
            july: 'កក្កដា',
            august: 'សីហា',
            september: 'កញ្ញា',
            october: 'តុលា',
            november: 'វិច្ឆកា',
            december: 'ធ្នូ',
            Internship:'ហាត់ការ',
            validation:'សុពុលភាព',
            todayAbsent:'អវត្តមានថ្ងៃនេះ',
            total: 'សរុប',
            No: "លេខរៀង",
        },
        position: {
            titleList: 'តារាងមុខតំណែង',
            search: 'ស្វែងរក',
            addPosition: 'បន្ថែម មុខដំណែង',
            tabelNotFound: 'មិនមានទិន្ន័យ',
            positionTable: 'មុខដំណែង',
            employeeCountTable: 'បុគ្គលិក',
            edit_delete: 'កែ | លុប',
            tablePagination: 'ចំនួនជួរនៃមួយទំព័រ',
            positionEmpProfile: 'រូបឬឈ្មោះកាត់',
            positionEmpName: 'ឈ្មោះបុគ្គលិក',
            formTitleAdd: 'បន្ថែម​ មុខដំណែង',
            formTitleEdit: 'កែប្រែ មុខដំណែង',
            txtPosition: 'ឈ្មោះមុខដំណែង',
            btnCancel: 'បោះបង់',
            btnSave: 'រក្សាទុក',
            btnDelete: 'លុប',
            deleteMessage: 'តើអ្នកពិតជាច្បាស់ថានិងលុប មុខដំណែង',
            deleteMessageWarning: 'បុគ្គលិកទាំងអស់ដែរកាន់មុខដំណែងនេះ និងត្រូវលុបទាំងអស់ផងដែរ',
            msgClose:'បិត',
            savedMsg: 'មុខដំណែងត្រូវបានរក្សាទុក',
            updateMsg: 'មុខដំណែងត្រូវបានកែប្រែ',
            deleteMsg: 'មុខដំណែងត្រូវបានលុប',
            // Modify by Huychoung 02/08/2023 #82
            notAllowedWarningMessage: 'អ្នកមិនអាចលុបមុខតំណែង',
            warningMessage: 'ព្រោះមុខតំណែងនេះត្រូវបានប្រើប្រាស់',
            parentPosition: 'មុខតំណែងមេ',
            Department: 'ផ្នែក',
        },
        employee: {
            employeeName: 'បុគ្គលិក',
            list: 'តារាងបុគ្គលិក',
            search: 'ស្វែងរក',
            btnAddEmp: 'បន្ថែមបុគ្គលិក',
            activeEmp: 'បុគ្គលិក នៅបំរើការងារ',
            inctiveEmp: 'បុគ្គលិក ឈប់ពីការងារ',
            tabAddEmp: 'បន្ថែមបុគ្គលិក',
            tbStaffCode: 'លេខកូដបុគ្គលិក',
            tbName: 'ឈ្មោះ',
            tbGender: 'ភេទ',
            tbGenderM: 'ប្រុស',
            tbGenderF: 'ស្រី',
            tbEmail: 'អ៊ីម៉ែល',
            tbOtherName: 'ឈ្មោះហៅក្រៅ',
            tbPosition: 'មុខដំណែង',
            tbShift: 'ម៉ោងការងារ',
            tbStartDate: 'ថ្ងៃចូលធ្វើការ',
            tbStartStopDate: 'ថ្ងៃចូល | ថ្ងៃឈប់',
            tbPhoneNum: 'លេខទូរស័ព្ទ',
            tbEditDelete: 'កែ | លុប',
            tabelNotFound: 'មិនមានទិន្ន័យ',
            tablePagination: 'ចំនួនជួរនៃមួយទំព័រ',
            frmAddEmp: 'បន្ថែម បុគ្គលិក',
            frmEditEmp: 'កែប្រែ បុគ្គលិក',
            staffCode: 'លេខកូដបុគ្គលិក',
            txtFirstName: 'នាមឈ្មោះ*',
            txtLastName: 'នាមត្រកូល*',
            genderF: 'ភេទស្រី',
            genderM: 'ភេទប្រុស',
            txtOtherName: 'ឈ្មោះហៅក្រៅ',
            role:'សិទ្ធ*',
            txtEmail: 'អ៊ីម៉ែល*',
            selectPosition: 'ជ្រើសរើស មុខដំណែង*',
            selectShift: 'ជ្រើសរើស​​ ម៉ោងការងារ*',
            txtStartDate: 'ថ្ងៃចូលធ្វើការ*',
            txtPhoneNum: 'លេខទូរស័ព្ទ*',
            txtUserID: 'លេខ​សម្គាល់​អ្នក​ប្រើប្រាស់ ឬ លេខទូរស័ព្ទ*',
            txtNationalID: 'លេខអត្តសញ្ញាណបណ្ណ',
            txtBirthDate: 'ថ្ងែខែឆ្នាំកំណើត',
            txtBirthPlace: 'ទីកន្លែងកំណើត',
            txtHouseNo: 'លេខផ្ទះ',
            txtStreetNo: 'លេខផ្លូវ',
            txtProvince: 'ខេត្ត',
            txtDistrict: 'ស្រុក',
            txtCommune : 'ឃុំ',
            txtVillage: 'ភូមិ',
            txtFacebook: 'ហ្វេសប៊ុក',
            txtTelegram: 'តេឡេក្រាម',
            txtOtherContact: 'ប្រព័ន្ធទំនាក់ទំនង',
            btnCancel: 'បោះបង់',
            btnSave: 'រក្សាទុក',
            empImage: 'ជ្រើសរើសរូបបុគ្គលិក',
            isInactive: 'ឈប់ពីការងារ',
            leavedDate: 'ថ្ងៃឈប់ពីការងា',
            january: 'មករា',
            february: 'កុម្ភះ',
            march: 'មិនា',
            april: 'មេសា',
            may: 'ឧសភា',
            june: 'មិថុនា',
            july: 'កក្កដា',
            august: 'សីហា',
            september: 'កញ្ញា',
            october: 'តុលា',
            november: 'វិច្ឆកា',
            december: 'ធ្នូ',
            btnDelete: 'លុប',
            deleteMessage: 'តើអ្នកពិតជាច្បាស់ថានិងលុបបុគ្គលិក',
            msgClose:'បិទ',
            savedMsg: 'បុគ្គលិកត្រូវបានរក្សាទុក',
            updateMsg: 'បុគ្គលិកត្រូវបានកែប្រែ',
            deleteMsg: 'បុគ្គលិកត្រូវបានលុប',
            AddEmp:'បន្ថែមបុគ្គលិក',
            tbChildName: 'ឈ្មោះកូន',
            ChildList: 'បញ្ជីរាយនាមកូន',
            EducationList: 'កម្រឹតសិក្សា',
            OtherSkillList: 'ជំនាញផ្សេងៗ',
            ExperienceList: 'បទពិសោធន៍ការងារ',
            LanguageList: 'ភាសា',
            ReferenceList: 'ឯកសារយោង',
            Remark: 'សំគាល់',
            tbSchoolName: 'ឈ្មោះសាលា' ,
            tbAddress: 'អាស័យដ្ធាន',
            tbStartDate: 'ថ្ងៃចាប់ផ្តើម',
            tbEndDate: 'ថ្ងៃបញ្ចប់',
            tbSkill: 'ជំនាញ',
            tbDetail: 'បរិយាយ',
            tbTrainingPlace: 'ឈ្មោះកន្លែងបណ្តុះបណ្តាល',
            txtPosition: 'តំណែង',
            tbLanguage: 'ភាសា',
            tbLevel: 'កម្រិត',
            tbCompany: 'ក្រុមហ៊ុន',
            ttFullName: 'ឈ្មោះអ្នកណែនាំ',
        },
        absent: {
            listTitle: 'តារាងស្នើរច្បាប់',
            search: 'ស្វែងរក',
            btnAdd: 'បន្ថែម អវត្តន៏មាន',
            tbEmp: 'បុគ្គលិក',
            tbAbsent: 'អវត្តន៏មាន',
            tbDay: 'ថ្ងៃ',
            tbDate: 'ថ្ងៃខែឆ្នាំ',
            tbDescription: 'ពិពណ៌នា',
            tbEdit_Delete: 'កែ | លុប',
            tbPagination: 'ចំនួនជួរនៃមួយទំព័រ',
            tabelNotFound: 'មិនមានទិន្ន័យ',
            fullDay: 'ពេញមួយថ្ងៃ',
            halfDay: 'កន្លះថ្ងៃ',
            morning: 'ពេលព្រឹក',
            afternoon: 'ពេលរសៀល',
            monday: 'ថ្ងៃចន្ទ',
            tuesday: 'ថ្ងៃអង្គារ',
            wednesday: 'ថ្ងៃពុធ',
            thursday: 'ថ្ងៃព្រហស្បតិ៍',
            friday: 'ថ្ងៃសុក្រ',
            saturday: 'ថ្ងៃសៅរ៍',
            sunday: 'ថ្ងៃអាទិត្យ',
            frmTitleAdd: 'បន្ថែមអវត្តន៏មាន',
            frmTitleEdit: 'កែប្រែអវត្តន៏មាន',
            frmSelect: 'ជ្រើសរើសបុគ្គលិក',
            frmFullDay: 'ពេញមួយថ្ងៃ',
            frmHalfDay: 'កន្លះថ្ងៃ',
            frmAbsentDate: 'ថ្ងៃខែ អវត្តន៏មាន',
            frmMorning: 'ពេលព្រឹក',
            frmAfternoon: 'ពេលរសៀល',
            frmDescription: 'ពិពណ៌នា',
            frmCancel: 'បោះបង់',
            frmSave: 'រក្សាទុក',
            january: 'មករា',
            february: 'កុម្ភះ',
            march: 'មិនា',
            april: 'មេសា',
            may: 'ឧសភា',
            june: 'មិថុនា',
            july: 'កក្កដា',
            august: 'សីហា',
            september: 'កញ្ញា',
            october: 'តុលា',
            november: 'វិច្ឆកា',
            december: 'ធ្នូ',
            deleteMsgQ: 'តើអ្នកប្រាកដដែរឬទេ?',
            deleteMsgAlert: 'លុបអវត្តន៏មានរបស់',
            deleteMsgAlertAbsen: "",
            btnCancel: 'បោះបង់',
            btnDelete: 'លុប',
            msgClose:'បិត',
            savedMsg: 'អវត្តន៏មានត្រូវបានរក្សាទុក',
            updateMsg: 'អវត្តន៏មានត្រូវបានកែប្រែ',
            deleteMsg: 'អវត្តន៏មានត្រូវបានលុប',
            today:'អវត្តមានថ្ងៃនេះ',
            reason:'មូលហេតុ',
            type:'ប្រភេទច្បាប់',
            remark:'សម្គាល់',
            btnApplyLeave:'ស្នើច្បាប់',
            btnSave:'រក្សាទុក',
            btnSubmit:'បញ្ចូន',
            attendance:'ថ្ងៃអវត្តមាន',
            absentTime:'ម៉ោងអវត្តមាន',
            LeaveDetail:'លម្អិត',
        },
        report: {
            title: 'របាយការណ៍',
            tbEmployee: 'បុគ្គលិក',
            tbAbsentCount: 'ចំនួន អវត្តន៏មាន',
            tbTotalAbsent: 'អវត្តន៏មានសរុប(ថ្ងៃ)',
            tbPosition: 'មុខដំណែង',
            tbAbsent: 'អវត្តន៏មាន',
            tbDay: 'ថ្ងៃ',
            tbDate: 'ថ្ងៃខែឆ្នាំ',
            tbDescription: 'ពិពណ៌នា',
            tbPagination: 'ចំនួនជួរនៃមួយទំព័រ',
            notReport: 'សូមជ្រើសរើស ថ្ងៃខែឬបុគ្គលិក ដើម្បីបង្ហាញលទ្ធផល',
            txtDate: 'ជ្រើសរើសថ្ងៃខែ',
            txtSelectEmp: 'ជ្រើសរើសបុគ្គលិក',
            smgAlert: 'សូមជ្រើសរើស ថ្ងៃខែណាមួយឬបុគ្គលិកណាម្នាក់',
            btnReport: 'របាយការណ៍',
            fullDay: 'ពេញមួយថ្ងៃ',
            halfDay: 'កន្លះថ្ងៃ',
            morning: 'ពេលព្រឹក',
            afternoon: 'ពេលរសៀល',
            day: 'ថ្ងៃ',
            monday: 'ថ្ងៃចន្ទ',
            tuesday: 'ថ្ងៃអង្គារ',
            wednesday: 'ថ្ងៃពុធ',
            thursday: 'ថ្ងៃព្រហស្បតិ៍',
            friday: 'ថ្ងៃសុក្រ',
            saturday: 'ថ្ងៃសៅរ៍',
            sunday: 'ថ្ងៃអាទិត្យ',
            january: 'មករា',
            february: 'កុម្ភះ',
            march: 'មិនា',
            april: 'មេសា',
            may: 'ឧសភា',
            june: 'មិថុនា',
            july: 'កក្កដា',
            august: 'សីហា',
            september: 'កញ្ញា',
            october: 'តុលា',
            november: 'វិច្ឆកា',
            december: 'ធ្នូ',
            pdfHeaderTb: 'តារាងអវត្តន៏មាន',
            pdfTitle: 'របាយការណ៍ អវត្តន៏មាន',
            pdfReportBy: 'ចេញរបាយការណ៍ដោយ',
            pdfDateReport:'ថ្ងៃខែចេញរបាយការណ៍'
        },
        user: {
            listTitle: 'តារាងអ្នកប្រើប្រាស់',
            btnAdd: 'បន្ថែម អ្នកប្រើប្រាស់',
            tbName: 'លេខ​សម្គាល់​អ្នក​ប្រើប្រាស់',
            tbEmail: 'អ៊ីមែល',
            tbRole: 'តួនាទី',
            tbPhoneNum: 'លេខទូរស័ព្ទ',
            tbUpdate_Delete: 'កែប្រែ | លុប',
            tbPagination: 'ចំនួនជួរនៃមួយទំព័រ',
            frmTitleAdd: 'បន្ថែម អ្នកប្រើប្រាស់',
            txtRole: 'តួនាទី',
            txtName: 'ឈ្មោះ',
            txtEmail: 'អ៊ីមែល',
            txtPhone: 'លេខទូរស័ព្ទ',
            txtPassword: 'ពាក្យសម្ងាត់',
            txtPasswordConfir: 'បញ្ជាក់ ពាក្យសម្ងាត់',
            txtImage: 'ជ្រើសរើសរូបភាព',
            btnCancel: 'បោះបង់',
            btnSave: 'រក្សាទុក',
            btnDelete: 'លុប',
            deleteMessage: 'តើអ្នកពិតជាច្បាស់ថានិងអ្នកប្រើប្រាស់',
            msgClose:'បិត',
            savedMsg: 'អ្នកប្រើប្រាស់ត្រូវបានរក្សាទុក',
            updateMsg: 'អ្នកប្រើប្រាស់ត្រូវបានកែប្រែ',
            deleteMsg: 'អ្នកប្រើប្រាស់ត្រូវបានលុប',
            txtUserID: 'លេខកូដអ្នកប្រើប្រាស់',
            txtUserName: 'ឈ្មោះអ្នកប្រើប្រាស់',
        },
        account: {
            tabAccount: 'គណនី',
            tabPassword: 'ពាក្យសម្ងាត់',
            txtName: 'ឈ្មោះ',
            txtEmail: 'អ៊ីមែល',
            Password: 'ពាក្យសម្ងាត់',
            txtPassword: 'ពាក្យសម្ងាត់',
            txtNewPassword: 'ពាក្យសម្ងាត់ថ្មី',
            txtConfirPassword: 'បញ្ជាក់ ពាក្យសម្ងាត់',
            btnSave: 'រក្សាទុក',
            msgClose:'បិត',
            updateMsg: 'គណនីត្រូវបានកែប្រែ',
            passUpdateMsg: 'ពាក្យសម្ងាត់ត្រូវបានកែប្រែ សូមធ្វើការចូលប្រព័ន្ធម្តងទៀត'
        },
        role: {
            role: 'សិទ្ធប្រើប្រាស់',
            tbRole: 'សិទ្ធ',
            tbMenu: 'ម៉ឺនុយ',
            tbDescription: 'ពិពណ៏នា',
            tbUser: 'អ្នកប្រើប្រាស់',
            frmNameAdd: 'បង្កើតសិទ្ធ',
            frmNameEdit: 'កែប្រែសិទ្ទ',
            txtRole: 'ឈ្មោសិទ្ធ',
            txtDescrition: 'ពិពណ៏នា',
            lblSelectMenu: 'ជ្រើសរើសម៉ឺនុយ',
            btnAddRole: 'បន្ថែមសិទ្ធ',
            btnCancel: 'បោះបង់',
            btnSave: 'រក្សាទុក',
        },
        workflow:{
            listWorkflow:'លំហូរការងារ',
            btnAdd:'បន្ថែម',
            group:'ក្រុម',
            frmTitle:'បន្ថែមលំហូការងារ',
            frmEditTitle:'កែប្រែលំហូរការងារ',
            workflowCode:'កូដលំហូការងារ',
            workflowName:'ឈ្មោះលំហូការងារ',
            groupCode:'កូដក្រុម',
            groupName:'ឈ្មោះក្រុម',
            user:'អ្នកប្រើប្រាស់',
            deleteMessage:'តើអ្នកពិតជាលុប',
            createDate:'ថ្ងៃបង្កើត',
            order:'លំដាប់',
            addTable:'សូមបញ្ចូលថ្ងៃខែនិងម៉ោង',
            groupTable: 'សូមបញ្ចូលឈ្មោះក្រុម',
            userGroup:'សូមជ្រើសរើសអ្នកប្រើប្រាស់',
            position:'សីមជ្រើសរើសមុខតំណែង',
            empity:'ឈ្មោះក្រុមមិនអនុញ្ញាតឲដូចគ្នា',
            btnClick: 'សូមចុចលើបូតុងនិងជ្រើសរើសថ្ងៃនិងម៉ោង ==>',
            labelPosition:'មុខតំណែង',
            NoPosition:'ប្រភេទច្បាប់មួយនេះគ្មានមុខតំណែងសម្រាប់បង្កើតលំហូរការងារទេ',
            labelWorkflowGroup:'ក្រុមលំហូរការងារ',
        },
        parameters: {
            listParameter:'តារាងអញ្ញតិ',
            frmTitle:'បន្ថែមអញ្ញតិ',
            parameter:'អញ្ញតិ',
            value1:'តម្លៃទី១',
            value2:'តម្លៃទី២',
            frmEditTitle:'កែប្រែអញ្ញតិ',
            txtValidation:'សុពលភាព',
            txtkh:'ខ្មែរ',
            txten:'អង់គ្លេស',
            txtth:'ថៃ',
            txtch:'ចិន',
            txtfr:'បារាំង',
            txtvn:'វៀតណាម',
        },
        leaveRequest:{
            list:'តារាងច្បាប់ដែលបានស្នើរសុំ',
            applied:'ច្បាប់ដែលបានស្នើរសុំ',
            history:'ប្រវត្តិ',
            btnApprove:'អនុញ្ញាត',
            btnReject:'បដិសេធ',
            detail:'លម្អិត',
            comment:'មតិយោបល',
            code:'កូដ',
            name:'ឈ្មោះ',
            section:'វេន',
            timeIn:'ម៉ោងចូល',
            timeOut:'ម៉ោងចេញ',
            frmAddtime:'បន្ថែមម៉ោងការងារ',
            frmEditTime:'កែប្រែម៉ោងការងារ',
            shiftList:'ផ្លាស់ប្ដូរ',
            msgClose:'បិទ',
            msgApprove:'ទន្និន៍យរបស់អ្នកត្រូវបានកែប្រែ',
            msgReject:'ទន្និន័យរបស់អ្នកត្រូវបានបដិសេធ',
        },
        leaveEntry:{    
            btnExport: 'ទាញយកឯកសារ',
            listLeaveEntry:'បញ្ជីអវត្តមាន',
            frmTitle:'បញ្ចូលអវត្តមាន',
            frmEditTitle:'កែប្រែអវត្តមាន',
            frmAdd: 'បន្ថែមបញ្ជីអវត្តមានតាមផ្នែក',
            frmEdit: 'កែប្រែបញ្ជីអវត្តមានតាមផ្នែក',
            department: 'ផ្នែក',
            tbAbsent:'ថ្ងៃអវត្តមាន',
            tbTime:'ម៉ោង',
            tbEmpName:'ឈ្មោះបុគ្គលិក',
            tbReason:'មូលហេតុ',
            tbStatus:'ស្ថានភាព',
            tbType:'ប្រភេទច្បាប់',
            tbRemark:'សម្គាល់',
            tbAttendanceDate:'ថ្ងៃអវត្តមាន',
            tbAction:'កែប្រែ|លុប',
            leaveReason:'មូលហេតុ',
            btnAdd:'បន្ថែមដោយផ្នែក',
            frmAddReason:'បន្ថែមមូលហេតុ',
            frmEditReasons:'កែប្រែមូលហតុ',
            frmLeaveType:'បន្ថែមប្រភេទច្បាប់',
            frmEditLeaveType:'កែប្រែប្រភេទច្បាប់',
            btnAddLeaveType:'បន្ថែម',
            txtAllowance:'ប្រាក់បន្ថែម',
            txtDeduction:'ប្រាក់កាត់', 
            submiteDate:"ថ្ងៃស្នើរសុំ",
            detail:'មើលបន្ថែម',
            msgSaved:'ទន្និន័យរបស់អ្នកត្រូវបានរក្សាទុក',
            msgDelete:'ទន្និន័យរបស់អ្នកត្រូវបានលុប',
            msgUpdate:'ទន្និន័យរបស់អ្នកត្រូវបានកែប្រែ',
            filterByDate: "Filter by date",
            startDate: "ចាប់ពីថ្ងៃ",
            endDate: "រហូតដល់ថ្ងៃ",
            filterByType: "Filter by type",
            quickFilter: "Quick filter",
            today: "ថ្ងៃនេះ",
            weekly: "ប្រចាំសប្ដាហ៍",
            monthly: "ប្រចាំខែ",
            yearly: "ប្រចាំឆ្នាំ",
            search: "ស្វែងរក",
            msgEmpity: 'សូមជ្រើសរើសយកថ្ងៃអវត្តមាននិងម៉ោង!!!',
            labelDateTime: "អវត្តមាន",
            msgExist: "ថ្ងៃអវត្តមាននិងម៉ោងនេះត្រូវបានបញ្ចូលរូចហើយ",
            msgDuplicate: "ថ្ងៃអវត្តមាននិងម៉ោងមិនអាចដូចគ្នា",
            validationDate: 'សូមបញ្ចូលថ្ងៃអវត្តមាន',
            validationTime: 'សូមបញ្ចូលម៉ោងអវត្តមាន',
            tbPermission: 'មានច្បាប់',
        },
        branch:{
            branchList:'សាខា',
            frmAddBranch:'បន្ថែមសាខា',
            frmEditBranch:'កែប្រែសាខា',
            txtCode:'លេខកូដ',
            txtBranch:'សាខា',
            txtLocation:'ទីតាំង',
            txtStartDate:'ថ្ងៃបង្កើត',
            txtEndDate:'ថ្ងៃបិទ',
        },
        menuSetting:{
            menuList:'បញ្ចី',
            frmAddMenu:'បន្ថែមបញ្ចី',
            frmEditMenu:'កែប្រែបញ្ចី',
            txtMenuCode:'លេខកូដ',
            menuName:'បញ្ចីឈ្មោះ',
            connection:'តំណរភ្ជាប់',
            MainCode:'លេខកូដមេ',
            Sign:'និមិត្តសញ្ញា',
            Type:'ប្រភេទ',
            Order:'លំដាប់',
            Closed:'បានបិទ',
        },
        department:{
            listDepartment:'តារាងផ្នែក',
            frmAddDepartment:'បន្ថែមផ្នែក',
            frmEditDepartment:'កែប្រែផ្នែក',
            department:'ផ្នែក',
            parentDepartment: 'ផ្នែកមេ',
            Remark: 'សម្គាល់',
            warningMessage: 'ត្រូវបានប្រើប្រាស់នៅក្នុង ៖',
        },
        document:{
            documentList: 'ឯកសារ',
            btnAdd: 'បន្ថែម',
            btnDelete: 'លុប',
            btnExport: 'នាំចេញ',
            frmAddDocument: 'បន្ថែមឯកសារ',
            frmDocumentCode: 'លេខកូដឯកសារ',
            frmTitle: 'ចំណងជើង',
            frmType: 'ប្រភេទឯកសារ',
            frmContentKH: 'មាតិកាខ្មែរ',
            frmContentEN: 'មាតិកាអង់គ្លេស',
            frmDescriptionKH: 'បរិយាយខ្មែរ',
            frmDescriptionEN: 'បរិយាយអង់គ្លេស',
            tbCheckbox: '',
            tbDocumentCode: 'លេខកូដឯកសារ',
            tbTitle: 'ចំណងជើង',
            tbType: 'ប្រភេទឯកសារ',
            tbContentKH: 'មាតិកាខ្មែរ',
            tbContentEN: 'មាតិកាអង់គ្លេស',
            tbDescriptionKH: 'បរិយាយខ្មែរ',
            tbDescriptionEN: 'បរិយាយអង់គ្លេស',
            tbAction: 'Action',
            DialogWarning: 'Please select an item',
            tbFileName: 'ឈ្មោះឯកសារ',
        },
        applyLeave:{
            msgEmpity: 'សូមជ្រើសរើសយកថ្ងៃអវត្តមាននិងម៉ោង!!!',
            msgDuplicate: 'ថ្ងៃអវត្តមាននិងម៉ោងមិនអាចដូចគ្នា',
            msgDateTime: 'សូមជ្រើសរើសថ្ងៃអវត្តមាននិងម៉ោង',
            msgExist: 'ថ្ងៃអវត្តមាននិងម៉ោងនេះត្រូវបានបញ្ចូលរូចហើយ',
            msgAttendance: 'សូមជ្រើសរើសយកថ្ងៃអវត្តមាន',
            labelDateTime: 'អវត្តមាន',
            msgTime:'សូមជ្រើសរើសយកម៉ោង',
        },
        systemLog:{
            tbActions: 'កែ | លុប',
            listSystemLog: 'ប្រព័ន្ធ​កត់ត្រាកំណត់ហេតុ',
            btnAddSystemLog: 'បន្ថែមកំណត់ហេតុ',
            tbMenuName: 'មុខងារ',
            tbUser: 'អ្នកប្រើប្រាស់',
            tbAction: 'សកម្មភាព',
            tbOldData: 'ទិន្នន័យចាស់',
            tbNewData: 'ទិន្នន័យថ្មី',
            tbLogType: 'ប្រភេទប្រវត្តិ',
            tbMessage: 'សារបញ្ហា',
            tbHostName: 'ឈ្មោះឧបករណ៌',
            tbDateTime: 'ថ្ងៃនិងម៉ោងកត់ត្រា',
        },
        shift: {
            labelDateTime: 'វេន​​ ម៉ោងចូល ​និងម៉ោងចេញ',
            msgEmpity: 'សូមជ្រើសរើសយកវេន​​ ម៉ោងចូល ​និងម៉ោងចេញ',
            msgDuplicate: 'ម៉ោងចូល ​និងម៉ោងចេញមិនអាចដូចគ្នាបានទេ',
            msgExist: 'ម៉ោងចូល ​និងម៉ោងចេញមានទិន្នន័យរួចហើយ',
        },
        staffShift: {
            addShift: 'បន្ថែមម៉ោងការងារ',
            editShift: 'កែប្រែម៉ោងការងារ',
            deleteShift: 'លុប',
            tbEmployeeName: 'ឈ្មោះបុគ្គលិក',
            tbShiftName: 'ម៉ោងការងារ',
            tbStartDate: 'ថ្ងៃចាប់ផ្តើម',
            tbEndDate: 'ថ្ងៃបញ្ចប់',
            tbRemark: 'សំគាល់',
        },
        staffResignation: {
            staffResign: 'បុគ្គលិកលាឈប់',
            addFrm: 'បន្ថែមបុគ្គលិកលាឈប់',
            editFrm: 'កែបុគ្គលិកលាឈប់',
            employeePKID: 'ឈ្មោះបុគ្គលិក',
            resignationReasonPKID: 'មូលហេតុគោល',
            description: 'ពណ៌នាបន្ថែម',
            resignedDate: 'ថ្ងៃលាឈប់',
        },
        resignationReason: {
            resignReason: 'មូលហេតុលាឈប់',
            addFrm: 'បន្ថែមមូលហេតុលាឈប់',
            editFrm: 'កែមូលហេតុលាឈប់',
            reasonCode: 'កូដ',
            description: 'មូលហេតុ', 
        },
    }
};
